let pdfFiller = require('pdffiller');

let sourcePDF = "./pdf/tlc-transfer-app.pdf";
let destinationPDF =  "./output/completed.pdf";

let data = {
   Name: 'Max De Jesus',
  DBA: '',
  'Mailing Address': '601 Carpenter Pl',
  City: 'Ridgefield',
  State: 'New Jersey',
  Zip: '07657',
  undefined_11: '',
  'Cell phone': '',
  undefined_12: '',
  undefined_13: '',
  'Other Telephone': '',
  undefined_14: '',
  undefined_15: '',
  'Email Address': '',
  'Residence Address No PO Boxes': '',
  City_2: '',
  State_2: '',
  Zip_2: '',
  'VEHICLE ID': '',
  'SEATING CAPACITY': '',
  PLATE: '',
  YEAR: '',
  MAKE: '',
  'IF YES GIVE THE NAME OF THE COACH BUILDER': '',
  'VEHICLE ID_2': '',
  YEAR_2: '',
  PLATE_2: '',
  MAKE_2: '',
  NAME: '',
  'MAILING ADDRESS': '',
  CITY: '',
  STATE: '',
  ZIP: '',
  undefined_20: '',
  undefined_21: '',
  undefined_22: '',
  'OF SHARES': '',
  SS_2: '',
  undefined_23: '',
  undefined_24: '',
  'DRIVER LICENSE': '',
  NAME_2: '',
  'MAILING ADDRESS_2': '',
  CITY_2: '',
  STATE_2: '',
  ZIP_2: '',
  undefined_25: '',
  undefined_26: '',
  undefined_27: '',
  'OF SHARES_2': '',
  SS_3: '',
  undefined_28: '',
  undefined_29: '',
  'DRIVER LICENSE_2': '',
  NAME_3: '',
  'MAILING ADDRESS_3': '',
  CITY_3: '',
  STATE_3: '',
  ZIP_3: '',
  undefined_30: '',
  undefined_31: '',
  undefined_32: '',
  'OF SHARES_3': '',
  SS_4: '',
  undefined_33: '',
  undefined_34: '',
  'DRIVER LICENSE_3': '',
  NAME_4: '',
  CITY_4: '',
  STATE_4: '',
  undefined_35: '',
  undefined_36: '',
  undefined_37: '',
  SS_5: '',
  undefined_38: '',
  undefined_39: '',
  'Company Name': '',
  'Secretary Print': '',
  Date: '',
  'and that there is an existing and current vehicle license issued by the TLC and that there have been no changes to the Business Entity structure for that current  existing': '',
  Name_2: '',
  Title: '',
  Date_2: '',
  Name_3: '',
  'Entity Name either applicant name  base or SHL permit holder': '',
  'with the vehicle identification number': '',
  'Print Name': '',
  Date_3: '',
  'Print Name_2': '',
  Date_4: '',
  'Print Name_3': '',
  Date_5: '',
  'DRIVER LICENSE_4': '',
  'OF SHARES_4': '',
  ZIP_4: '',
  'MAILING ADDRESS_4': '',
  Group4: '',
  Group5: '',
  Group6: '',
  Group7: '',
  Group8: '',
  Group9: '',
  Group10: '',
  Group11: '',
  Group12: '',
  Group13: '',
  Group14: '',
  Group15: '',
  Group16: '',
  Group17: '',
  Group18: '',
  Group19: '',
  Group20: '',
  Group21: '',
  Group22: '',
  Group23: '',
  Group24: '',
  Group25: '',
  Button5: '',
  'BASE  AUTHORITY NAME': '',
  'BASE LICENSE': '',
  'BASE  AUTHORITY NAME_2': '',
  'BASE LICENSE_2': '',
  'SHL PERMIT ENTITY NAME': '',
  'SHL PERMIT': '',
  'SHL PERMIT ENTITY NAME_2': '',
  'SHL PERMIT_2': '' }
}
